spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: behama25
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
    default-schema: tasklist

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

security:
  jwt:
    secret: ZmphZGtsZGZqYWRrbGZqYWtsZGpmYWtsamRma2xhanNma2xqYWRrbHNmamFrbHNmag
    access: 360000
    refresh: 2592000000

springdoc:
  override-with-generic-response: false